# -*- coding: utf-8 -*-
"""number_plate_detect.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cQET0EHWj917DBSEO3mrtHClm4N8u7Zz
"""

!pip install ultralytics

import ultralytics
import os
import shutil
from tqdm.notebook import tqdm

train_images = len(os.listdir("/content/drive/MyDrive/License-Plate/License-Plate-Data/train/images"))
train_labels = len(os.listdir("/content/drive/MyDrive/License-Plate/License-Plate-Data/train/labels"))

test_images = len(os.listdir("/content/drive/MyDrive/License-Plate/License-Plate-Data/test/images"))
test_labels = len(os.listdir("/content/drive/MyDrive/License-Plate/License-Plate-Data/test/labels"))

print("Train images:", train_images)
print("Train labels:", train_labels)

print("Test images:", test_images)
print("Test labels:", test_labels)

!yolo task=detect mode=train model=yolov8s.pt data=/content/drive/MyDrive/License-Plate/License-Plate-Data/data.yaml epochs=10 batch=8 project=/content/drive/MyDrive/License-Plate/License-Plate-Data/training_results name=numberplate

!yolo task=detect mode=predict model=/content/drive/MyDrive/License-Plate/License-Plate-Data/training_results/numberplate/weights/best.pt conf=0.5 source=/content/drive/MyDrive/License-Plate/License-Plate-Data/test_images

!cp -r /content/runs/detect/predict/ /content/drive/MyDrive/License-Plate/License-Plate-Data/test_images_output